/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.Dao_contacto;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Contacto;

/**
 *
 * @author jbila
 */
public class FrmContacto extends javax.swing.JFrame {

    private final Dao_contacto dao_contacto;

    /**
     * Creates new form FrmContacto
     */
    public FrmContacto() {
        initComponents();
        dao_contacto = new Dao_contacto();
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblContacto = new javax.swing.JTable();
        btnPrint = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Grey"));
        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-home-24.png"))); // NOI18N
        jLabel1.setText("CONTACTOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 40));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 78, 90, 20));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel3.setText("Nome");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 118, 90, 20));

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel4.setText("Telefone");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 148, 90, 30));

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 188, 90, 30));

        txtId.setEditable(false);
        txtId.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 400, 30));
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 400, 30));

        jTextField3.setText("jTextField2");
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 320, 30));

        jTextField4.setText("jTextField1");
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 320, 30));
        getContentPane().add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 400, 30));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 400, 30));

        btnSave.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        btnSave.setText("gravar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 130, 30));

        btnUpdate.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btnUpdate.setText("editar");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 130, 30));

        btnDelete.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        btnDelete.setText("eliminar");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 130, 30));

        tblContacto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Email", "Telefone"
            }
        ));
        tblContacto.setSelectionForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        tblContacto.setShowGrid(true);
        tblContacto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblContactoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblContacto);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 660, 190));

        btnPrint.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-print-24.png"))); // NOI18N
        btnPrint.setText("print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 130, 30));

        txtSearch.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        txtSearch.setToolTipText("INTRODUZA O NOME PARA BUSCA");
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 244, 570, 40));

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-eye-24.png"))); // NOI18N
        jLabel6.setText("BUSCA");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        save();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        delete();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblContactoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblContactoMouseClicked
        selection();
    }//GEN-LAST:event_tblContactoMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        update();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        JOptionPane.showMessageDialog(btnPrint, "SOON");
    }//GEN-LAST:event_btnPrintActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        if (!txtSearch.getText().isEmpty()) {
            List<Contacto> contactos = dao_contacto.findBy(txtSearch.getText());
            shwoInfo(contactos);
        } else {
            preencherTabela();
        }

    }//GEN-LAST:event_txtSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                FrmContacto frame = new FrmContacto();
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);
                frame.setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTable tblContacto;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    private void save() {
        Contacto contacto = new Contacto();
        contacto.setNome(txtNome.getText());
        contacto.setEmail(txtEmail.getText());
        contacto.setContacto(txtTelefone.getText());

        try {

            if (!txtNome.getText().isEmpty() && !txtEmail.getText().isEmpty()) {
                dao_contacto.add(contacto);
                limpar();
                preencherTabela();
            } else {
                JOptionPane.showMessageDialog(btnSave, "Preencha os campos");
            }

        } catch (Exception ex) {
            // TODO Auto-generated catch block
            ex.printStackTrace();
        }
    }

    private void limpar() {
        txtNome.setText("");
        txtTelefone.setText("");
        txtEmail.setText("");
    }

    private void preencherTabela() {
        /* DefaultTableModel model = (DefaultTableModel) tblContacto.getModel();
        Object[] row = new Object[4];
        model.setRowCount(0);// limpar a tabela
         */
        List<Contacto> contactos = dao_contacto.getAll();
        shwoInfo(contactos);
        /*
        for (int i = 0; i < contactos.size(); i++) {
            row[0] = contactos.get(i).getId();
            row[1] = contactos.get(i).getNome();
            row[2] = contactos.get(i).getContacto();
            row[3] = contactos.get(i).getEmail();
            model.addRow(row);
        }
         */
    }

    public void shwoInfo(List<Contacto> contactos) {
        DefaultTableModel model = (DefaultTableModel) tblContacto.getModel();
        Object[] row = new Object[4];
        model.setRowCount(0);// limpar a tabela
        for (int i = 0; i < contactos.size(); i++) {
            row[0] = contactos.get(i).getId();
            row[1] = contactos.get(i).getNome();
            row[2] = contactos.get(i).getContacto();
            row[3] = contactos.get(i).getEmail();
            model.addRow(row);
        }
    }

    /*--------------------------------------------------------------*/
    private void selection() {
        try {
            int selectedRow = tblContacto.getSelectedRow();
            if (selectedRow >= 0) {
                Object id = tblContacto.getValueAt(selectedRow, 0);
                Object nome = tblContacto.getValueAt(selectedRow, 1);
                Object telefone = tblContacto.getValueAt(selectedRow, 2);
                Object email = tblContacto.getValueAt(selectedRow, 3);

                txtId.setText(id.toString());
                txtNome.setText(nome.toString());
                txtTelefone.setText(telefone.toString());
                txtEmail.setText(email.toString());

            }
        } catch (NullPointerException ex) {

        }

    }

    private void delete() {
        if (!txtId.getText().isEmpty()) {
            int confirmation = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this record?",
                    "Confirm Deletion", JOptionPane.YES_NO_OPTION);
            if (confirmation == JOptionPane.YES_OPTION) {
                dao_contacto.removerContacto(Integer.valueOf(txtId.getText()));
                preencherTabela();
                limpar();
            } else {

                JOptionPane.showMessageDialog(tblContacto, "Selecione a linha na tabela");
            }

        }

    }

    private void update() {
        if (!txtId.getText().isEmpty()) {
            Contacto contacto = new Contacto();
            contacto.setId(Integer.valueOf(txtId.getText()));
            contacto.setNome(txtNome.getText());
            contacto.setEmail(txtEmail.getText());
            contacto.setContacto(txtTelefone.getText());
            try {
                dao_contacto.updateContacto(contacto);
                preencherTabela();
            } catch (SQLException e1) {
                // TODO Auto-generated catch block
                e1.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(btnUpdate, "Selecione a linha na Tabela");
        }

    }

}
